<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <RootNamespace>Plugin</RootNamespace>
    <Version>1.1.0</Version>
    <AssemblyTitle>LongNight</AssemblyTitle>
    <Company></Company>
    <Product>LongNight</Product>
    <Copyright>Copyright © hufang360 2026</Copyright>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageLicenseExpression></PackageLicenseExpression>
    <Authors>hufang360</Authors>
    <Description>永夜控制 / 满月 / 黎明事件</Description>
    <PackageId>LongNight</PackageId>
    <AssemblyName>LongNight</AssemblyName>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591;MSB3270</NoWarn>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <!-- <PackageReference Include="TShock" Version="6.1.0" /> -->
    <Reference Include="OTAPI">
      <HintPath>../lib/1458/OTAPI.dll</HintPath>
    </Reference>
    <Reference Include="TerrariaServer">
      <HintPath>../lib/1458/TerrariaServer.dll</HintPath>
    </Reference>
    <Reference Include="TShockAPI">
      <HintPath>../lib/1458/TShockAPI.dll</HintPath>
    </Reference>
    <Reference Include="ModFramework">
      <HintPath>../lib/1458/ModFramework.dll</HintPath>
    </Reference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
